// SPDX-License-Identifier: Apache-2.0

import * as vscode from 'vscode';
import type { MdlSourceContentProvider } from './extension';
import { resolvedMxcliPath } from './extension';
import { generateElk, generateMermaid, findMprFile } from './preview/mxcliRunner';
import { getElkWebviewContent } from './preview/elkTemplate';
import { getMermaidWebviewContent } from './preview/mermaidTemplate';

/**
 * MdlPreviewProvider manages a WebviewPanel that renders Mermaid diagrams
 * and ELK.js module overview graphs generated by mxcli.
 */
export class MdlPreviewProvider {
	private panel: vscode.WebviewPanel | undefined;
	private mxcliPath!: string;
	private mprPath: string | undefined;
	private diagramTheme!: string;
	private sourceProvider: MdlSourceContentProvider | undefined;

	// Sync state for diagram-with-source mode
	private activeSourceMap: Record<string, { startLine: number; endLine: number }> = {};
	private activeEditor: vscode.TextEditor | undefined;
	private selectionDisposable: vscode.Disposable | undefined;
	private highlightDecoration: vscode.TextEditorDecorationType;

	constructor(sourceProvider?: MdlSourceContentProvider) {
		this.sourceProvider = sourceProvider;
		this.highlightDecoration = vscode.window.createTextEditorDecorationType({
			backgroundColor: new vscode.ThemeColor('editor.findMatchHighlightBackground'),
			isWholeLine: true,
		});
		this.updateConfig();
	}

	updateConfig(): void {
		const config = vscode.workspace.getConfiguration('mdl');
		this.mxcliPath = resolvedMxcliPath();
		const configured = config.get<string>('mprPath', '');
		this.mprPath = configured || undefined;
		this.diagramTheme = config.get<string>('diagramTheme', 'clean');
	}

	/**
	 * Shows a diagram for the given element type and qualified name.
	 * For systemoverview, renders an ELK.js graph. Otherwise, renders Mermaid.
	 * The optional originalType preserves the original tree node type before mapping.
	 */
	async showDiagram(elementType: string, qualifiedName: string, originalType?: string): Promise<void> {
		const mprFile = await findMprFile(this.mprPath);
		if (!mprFile) {
			vscode.window.showErrorMessage('No .mpr file found. Set mdl.mprPath in settings.');
			return;
		}

		const effectiveType = originalType || elementType;

		if (effectiveType === 'systemoverview' || effectiveType === 'domainmodel' || effectiveType === 'entity' || effectiveType === 'microflow' || effectiveType === 'nanoflow' || effectiveType === 'page') {
			// ELK path — entity type uses 'entity' elementType so the backend
			// receives a qualified name (Module.Entity) and renders a focused view
			const jsonData = await generateElk(this.mxcliPath, mprFile, elementType, qualifiedName);
			if (!jsonData) {
				return;
			}

			let title: string;
			if (effectiveType === 'systemoverview') {
				title = 'System Overview';
			} else if (effectiveType === 'domainmodel') {
				title = `Domain Model: ${qualifiedName}`;
			} else if (effectiveType === 'microflow') {
				title = `Microflow: ${qualifiedName}`;
			} else if (effectiveType === 'nanoflow') {
				title = `Nanoflow: ${qualifiedName}`;
			} else if (effectiveType === 'page') {
				title = `Page: ${qualifiedName}`;
			} else {
				title = `Entity: ${qualifiedName}`;
			}
			this.ensurePanel(title);
			this.panel!.webview.html = getElkWebviewContent(jsonData, title, this.diagramTheme);

			// Handle messages from webview
			this.panel!.webview.onDidReceiveMessage(async (msg: any) => {
				if (msg.type === 'openModule' && msg.moduleName) {
					await this.showDiagram('entity', msg.moduleName, 'domainmodel');
				} else if (msg.type === 'openEntity' && msg.entityName) {
					// Navigate to a focused entity diagram if it contains a dot (qualified)
					if (msg.entityName.includes('.')) {
						await this.showDiagram('entity', msg.entityName);
					}
				}
			});
		} else {
			// Mermaid path
			const mermaidSource = await generateMermaid(this.mxcliPath, elementType, qualifiedName, mprFile);
			if (!mermaidSource) {
				return;
			}

			const title = `Diagram: ${qualifiedName}`;
			this.ensurePanel(title);
			this.panel!.webview.html = getMermaidWebviewContent(mermaidSource, qualifiedName, this.diagramTheme);
		}
	}

	/**
	 * Shows a synchronized diagram + MDL source side-by-side.
	 * MDL source opens in the left editor, ELK diagram in a right webview panel.
	 * Clicking a node highlights the corresponding MDL lines, and vice versa.
	 */
	async showDiagramWithSource(elementType: string, qualifiedName: string, originalType?: string): Promise<void> {
		const mprFile = await findMprFile(this.mprPath);
		if (!mprFile) {
			vscode.window.showErrorMessage('No .mpr file found. Set mdl.mprPath in settings.');
			return;
		}

		const jsonData = await generateElk(this.mxcliPath, mprFile, elementType, qualifiedName);
		if (!jsonData) {
			return;
		}

		let data: any;
		try {
			data = JSON.parse(jsonData);
		} catch {
			vscode.window.showErrorMessage('Failed to parse ELK JSON data.');
			return;
		}

		const mdlSource = data.mdlSource || '';
		const sourceMap = data.sourceMap || {};

		if (!this.sourceProvider || !mdlSource) {
			// Fall back to regular diagram if no source available
			const effectiveType = originalType || elementType;
			let title: string;
			if (effectiveType === 'domainmodel') {
				title = `Domain Model: ${qualifiedName}`;
			} else if (effectiveType === 'microflow') {
				title = `Microflow: ${qualifiedName}`;
			} else if (effectiveType === 'nanoflow') {
				title = `Nanoflow: ${qualifiedName}`;
			} else if (effectiveType === 'page') {
				title = `Page: ${qualifiedName}`;
			} else {
				title = `Entity: ${qualifiedName}`;
			}
			this.ensurePanel(title);
			this.panel!.webview.html = getElkWebviewContent(jsonData, title, this.diagramTheme);
			return;
		}

		// 1. Open MDL source in left editor
		const uri = this.sourceProvider.setContent(qualifiedName, mdlSource);
		const doc = await vscode.workspace.openTextDocument(uri);
		await vscode.languages.setTextDocumentLanguage(doc, 'mdl');
		const editor = await vscode.window.showTextDocument(doc, vscode.ViewColumn.One, false);

		// 2. Open ELK webview in right panel
		const effectiveType = originalType || elementType;
		let title: string;
		if (effectiveType === 'domainmodel') {
			title = `Domain Model: ${qualifiedName}`;
		} else if (effectiveType === 'microflow') {
			title = `Microflow: ${qualifiedName}`;
		} else if (effectiveType === 'nanoflow') {
			title = `Nanoflow: ${qualifiedName}`;
		} else if (effectiveType === 'page') {
			title = `Page: ${qualifiedName}`;
		} else {
			title = `Entity: ${qualifiedName}`;
		}

		if (this.panel) {
			this.panel.reveal(vscode.ViewColumn.Two);
			this.panel.title = title;
		} else {
			this.panel = vscode.window.createWebviewPanel(
				'mendixDiagram',
				title,
				vscode.ViewColumn.Two,
				{
					enableScripts: true,
					retainContextWhenHidden: true,
				}
			);
			this.panel.onDidDispose(() => {
				this.panel = undefined;
				this.cleanupSync();
			});
		}
		this.panel.webview.html = getElkWebviewContent(jsonData, title, this.diagramTheme);

		// 3. Store sync state
		this.activeSourceMap = sourceMap;
		this.activeEditor = editor;

		// 4. Handle messages from webview (node clicks)
		this.panel.webview.onDidReceiveMessage(async (msg: any) => {
			if (msg.type === 'nodeClicked' && msg.nodeId) {
				const range = this.activeSourceMap[msg.nodeId];
				if (range && this.activeEditor) {
					const startPos = new vscode.Position(range.startLine, 0);
					const endPos = new vscode.Position(range.endLine + 1, 0);
					const vscRange = new vscode.Range(startPos, endPos);
					this.activeEditor.setDecorations(this.highlightDecoration, [vscRange]);
					this.activeEditor.revealRange(vscRange, vscode.TextEditorRevealType.InCenter);
				}
			} else if (msg.type === 'openModule' && msg.moduleName) {
				await this.showDiagram('entity', msg.moduleName, 'domainmodel');
			} else if (msg.type === 'openEntity' && msg.entityName) {
				if (msg.entityName.includes('.')) {
					await this.showDiagram('entity', msg.entityName);
				}
			}
		});

		// 5. Editor -> Diagram sync (cursor move highlights node)
		this.setupSync();
	}

	private setupSync(): void {
		this.selectionDisposable?.dispose();
		this.selectionDisposable = vscode.window.onDidChangeTextEditorSelection((e) => {
			if (e.textEditor !== this.activeEditor) {
				return;
			}
			const line = e.selections[0].active.line;

			for (const [nodeId, range] of Object.entries(this.activeSourceMap)) {
				if (line >= range.startLine && line <= range.endLine) {
					this.panel?.webview.postMessage({ type: 'highlightNode', nodeId });
					return;
				}
			}
			// No match — clear highlights
			this.panel?.webview.postMessage({ type: 'highlightNode', nodeId: null });
		});
	}

	private cleanupSync(): void {
		this.selectionDisposable?.dispose();
		this.selectionDisposable = undefined;
		this.activeEditor = undefined;
		this.activeSourceMap = {};
	}

	dispose(): void {
		this.cleanupSync();
		this.highlightDecoration.dispose();
		if (this.panel) {
			this.panel.dispose();
			this.panel = undefined;
		}
	}

	private ensurePanel(title: string): void {
		if (this.panel) {
			this.panel.reveal(vscode.ViewColumn.Beside);
			this.panel.title = title;
		} else {
			this.panel = vscode.window.createWebviewPanel(
				'mendixDiagram',
				title,
				vscode.ViewColumn.Beside,
				{
					enableScripts: true,
					retainContextWhenHidden: true,
				}
			);
			this.panel.onDidDispose(() => {
				this.panel = undefined;
			});
		}
	}
}
